### ISSUE TITLE
what is the dataset directory?

### ISSUE THREAD

**Issue by manvirvirk** [ojedaa/UnetBinarySegmentation#1]

**Comment by ojedaa** [comment]
In Training.py:

#example of how to locate RGB input images=> training/img/

train_path = "training"# folder or path
image_folder = "img" #folder to img
label_folder = "lbl" #folder to label

#same for validation set
#example of how to locate RGB input images=> crossvalidation/img/

valid_path =  "crossvalidation"
valid_image_folder ="img"
valid_label_folder = "lbl"

**Comment by ojedaa** [comment]
I’m not providing a dataset to test this code. Use one of yourself.

**Comment by manvirvirk** [comment]
where to add these code lines???

**Comment by manvirvirk** [comment]
got it
